import os
from pathlib import Path
import subprocess
import sys
import tempfile
import unittest


ROOT = Path(__file__).resolve().parents[2]
SYNTAX_CHECK = ROOT / "scripts/check-python-syntax.py"
BASELINE_CHECK = ROOT / "scripts/check-baseline.sh"


class SyntaxCheckerTests(unittest.TestCase):
    def test_baseline_rejects_generated_python_artifacts(self):
        baseline = BASELINE_CHECK.read_text(encoding="utf-8")

        self.assertRegex(
            baseline,
            r"(?m)^generated_python_artifacts=\$\($",
        )
        self.assertRegex(
            baseline,
            r'(?m)^  printf .*"Python verification must leave no generated bytecode artifacts:"',
        )

    def test_checks_syntax_without_writing_bytecode(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            temporary_root = Path(temporary_directory)
            source = temporary_root / "valid.py"
            cache_root = temporary_root / "cache"
            source.write_text("value = 1\n", encoding="utf-8")
            env = os.environ.copy()
            env["PYTHONDONTWRITEBYTECODE"] = "1"
            env["PYTHONPYCACHEPREFIX"] = str(cache_root)

            result = subprocess.run(
                [sys.executable, str(SYNTAX_CHECK), str(source)],
                env=env,
                capture_output=True,
                text=True,
                timeout=30,
            )

            self.assertEqual(0, result.returncode, result.stderr)
            cache_files = [path for path in cache_root.rglob("*") if path.is_file()]
            self.assertEqual([], cache_files)

    def test_rejects_invalid_syntax(self):
        with tempfile.TemporaryDirectory() as temporary_directory:
            source = Path(temporary_directory) / "invalid.py"
            source.write_text("def broken(:\n", encoding="utf-8")

            result = subprocess.run(
                [sys.executable, str(SYNTAX_CHECK), str(source)],
                capture_output=True,
                text=True,
                timeout=30,
            )

            self.assertEqual(1, result.returncode)
            self.assertIn("check-python-syntax:", result.stderr)


if __name__ == "__main__":
    unittest.main()
